mv tile_0.png tile_0_bkp.png
mv tile_1.png tile_1_bkp.png
mv tile_2.png tile_2_bkp.png
mv tile_3.png tile_3_bkp.png
mv tile_4.png tile_4_bkp.png
mv tile_5.png tile_5_bkp.png
mv tile_6.png tile_6_bkp.png
mv tile_7.png tile_7_bkp.png
mv tile_8.png tile_8_bkp.png
mv tile_9.png tile_9_bkp.png
mv tile_10.png tile_10_bkp.png
mv tile_11.png tile_11_bkp.png
mv tile_12.png tile_12_bkp.png
mv tile_13.png tile_13_bkp.png
mv tile_14.png tile_14_bkp.png
mv tile_15.png tile_15_bkp.png
mv tile_16.png tile_16_bkp.png
mv tile_17.png tile_17_bkp.png
